# Handling Imbalanced Dataset

##### 1. Up Sampling
##### 2. Down Sampling

In [1]:
import numpy as np
import pandas as pd

# set the random seed for reproudcibility
np.random.seed(143)

# create a dataframe with two classed
n_samples = 1000
class_0_ratio = 0.9

n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0, n_class_1

(900, 100)

In [3]:
class_0 = pd.DataFrame({
    'feaure_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feaure_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feaure_1' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'feaure_2' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'target' : [1] * n_class_1
})

In [4]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [5]:
df

     feaure_1  feaure_2  target
0   -0.833154  0.265119       0
1    1.237691  2.975822       0
2   -2.475731 -1.933782       0
3   -1.038631  0.227639       0
4    0.994645 -0.427055       0
..        ...       ...     ...
995  2.298504  2.447442       1
996  0.593381  0.590848       1
997  1.428099  1.839045       1
998  3.051683  0.844221       1
999  3.243241  3.817542       1

[1000 rows x 3 columns]

In [6]:
df.head()

   feaure_1  feaure_2  target
0 -0.833154  0.265119       0
1  1.237691  2.975822       0
2 -2.475731 -1.933782       0
3 -1.038631  0.227639       0
4  0.994645 -0.427055       0

In [7]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [8]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [9]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_minority, replace=True, # sample will be added
        n_samples = len(df_majority), random_state = 42)

In [10]:
df_minority_upsampled.shape

(900, 3)

In [11]:
final_df = pd.concat([df_minority_upsampled, df_majority]).reset_index(drop=True)

In [12]:
len(final_df[final_df['target']==0])

900

In [13]:
# downsample

df_majority_downsampled = resample(df_majority, replace = False, 
                              n_samples = len(df_minority), random_state = 42)

In [15]:
df_majority_downsampled.shape

(100, 3)

In [17]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled]).reset_index(drop=True)
df_downsampled.shape

(200, 3)