# Data Encoding

#### 1. Nominal /One Hot Encoding
#### 2. Label and Ordinal Encoding
#### 3. Target Guided Ordinal Encoding

## Nominal/One Hot Encoding

#### Encoding is converting categorical data into a meaningful numerical value so that machine learning algorithm can understand and process it

#### One Hot Encoding creates a new column for every unique category and represent the presence of the cateogry with 1 and absence with 0

#### Red [0,0, 1]
#### Green [0, 1, 0]
#### Blue [1, 0, 0]

# Disadvantages

#### 1. Number of Features - for n number of unique categories it creates n number of columns

#### 2. Sparse Matrix - the matrix contains 0's and 1's, leads to overfitting

In [2]:
df.head()

   color
0    red
1   blue
2  green
3  green
4   blue

In [3]:
# create a instance of one hot encoder

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['color']]).toarray()

In [4]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [5]:
encoded_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [6]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         1.0          0.0        0.0
5         0.0          0.0        1.0
6         0.0          0.0        1.0
7         0.0          0.0        1.0
8         0.0          1.0        0.0

In [7]:
encoder.transform([['blue']]).toarray()

C:\Users\CIT\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [8]:
encoder.transform([['red']]).toarray()

C:\Users\CIT\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1.]])

In [9]:
final_df = pd.concat([df, encoded_df], axis = 1)

In [10]:
final_df

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4   blue         1.0          0.0        0.0
5    red         0.0          0.0        1.0
6    red         0.0          0.0        1.0
7    red         0.0          0.0        1.0
8  green         0.0          1.0        0.0

In [11]:
import seaborn as sns
dataset = sns.load_dataset('tips')

In [12]:
dataset

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
sex_encoder = OneHotEncoder()

In [14]:
sex_encoded = sex_encoder.fit_transform(dataset[['sex']]).toarray()

In [15]:
sex_encoded_df = pd.DataFrame(sex_encoded, columns = sex_encoder.get_feature_names_out())

In [16]:
sex_encoded_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [17]:
smoker_encoder = OneHotEncoder()

In [18]:
smoker_encoded = smoker_encoder.fit_transform(dataset[['smoker']]).toarray()

In [19]:
smoker_encoded_df = pd.DataFrame(smoker_encoded, columns = smoker_encoder.get_feature_names_out())

In [20]:
smoker_encoded_df

     smoker_No  smoker_Yes
0          1.0         0.0
1          1.0         0.0
2          1.0         0.0
3          1.0         0.0
4          1.0         0.0
..         ...         ...
239        1.0         0.0
240        0.0         1.0
241        0.0         1.0
242        1.0         0.0
243        1.0         0.0

[244 rows x 2 columns]

In [21]:
df = pd.concat([dataset, sex_encoded_df, smoker_encoded_df], axis = 1)

In [22]:
df

,total_bill,tip,sex,smoker,day,time,size,sex_Female,sex_Male,smoker_No,smoker_Yes
0,16.99,1.01,Female,No,Sun,Dinner,2,1.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,1.0,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,1.0,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,1.0,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0.0,1.0,1.0,0.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,1.0,0.0,0.0,1.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0.0,1.0,0.0,1.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0.0,1.0,1.0,0.0
243,18.78,3.00,Female,No,Thur,Dinner,2,1.0,0.0,1.0,0.0